name: "New Content Idea/Request 💡"
description: Share an idea for new content.
labels: [
  "add new content"
]
body:
  - type: markdown
    attributes:
      value: "## Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!"
  - type: input
    id: subject
    attributes:
      label: 📚 Subject area/topic
      description: Documentation area/topic (e.g. SSR, CMS guide, environment variables)
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 Suggested page"
      description: Please provide the URL of the page(s) or section where this idea would fit.
      placeholder: https://docs.staticsnap.com/en/getting-started/
    validations:
        required: true
  - type: textarea
    id: generalDesc
    attributes:
      label: "📋 General description or bullet points (if proposing new content)"
      description: Please provide a general description or bullet points about what you would like to see added.
      placeholder: "..."
    validations:
        required: true
  